# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tag Version

on:
  push:
    branches: ["develop", "feature/*", "!master"]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Version
        run: |
          echo "$(cat package.json)" | jq .version | xargs -I {} "Version="{} >> $GITHUB_ENV

      - name: Tag to ${{ env.Version }}
        run: |
          echo ${{ env.Version }}

      - name: Exit if not on master branch
        if: endsWith(github.ref, 'master') == false
        run: exit -1
